name: nothing here

on:
  push:
    branches: [ main ]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello there..!"
      - name: Display about OS info
        run: cat /etc/*release*
      - name: Dispaly the github context
        run: echo "${{ github }}"
      - name: Dispaly the github context with expression
        run: echo "${{ toJSON(github) }}"

